version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DB_USER=default_user
      - DB_PASS=pass
      - DB_NAME=todo
    hostname: postgres-local
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  server:
    container_name: todo-server
    image: todo/server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres-local
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm run dev